<#
.SYNOPSIS
Regenerates src/Portmark.Core/Usb/usb-vendors.tsv from the USB ID Repository's usb.ids.

.DESCRIPTION
Keeps the vendor lines only (four hex digits and the name registered to them) and drops every
product, interface and class line, which portmark has no use for and which would triple the size
of the table.

usb.ids carries no licence text of its own. The repository states its terms on
http://www.linux-usb.org/usb-ids.html: GPL-2.0-or-later or BSD-3-Clause, at the user's choice.
portmark uses it under BSD-3-Clause. Check that page still says so before committing a refresh,
and update the version and date in THIRD-PARTY-NOTICES.md to match the header this script writes.

.PARAMETER Source
A URL or a local path to usb.ids. Defaults to the canonical download.

.EXAMPLE
pwsh scripts/update-usb-vendors.ps1
pwsh scripts/update-usb-vendors.ps1 -Source C:\temp\usb.ids
#>
param(
    [string]$Source = 'http://www.linux-usb.org/usb.ids'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repo = Split-Path -Parent $PSScriptRoot
$target = Join-Path $repo 'src/Portmark.Core/Usb/usb-vendors.tsv'

if ($Source -match '^https?://') {
    $downloaded = Join-Path ([System.IO.Path]::GetTempPath()) 'portmark-usb.ids'
    Invoke-WebRequest -Uri $Source -OutFile $downloaded -UseBasicParsing
    $path = $downloaded
}
else {
    $path = $Source
}

$lines = [System.IO.File]::ReadAllLines($path, [System.Text.UTF8Encoding]::new($false))

$version = $null
$date = $null
$vendors = [System.Collections.Generic.SortedDictionary[int, string]]::new()

foreach ($line in $lines) {
    if ($line -match '^#\s*Version:\s*(\S+)') { $version = $Matches[1]; continue }
    if ($line -match '^#\s*Date:\s*(.+?)\s*$') { $date = $Matches[1]; continue }

    # The device class list follows the vendors. Its lines start with a letter, so the pattern
    # below would not match them anyway, but stopping here means a later section that happens
    # to start with four hex digits can never be mistaken for a vendor.
    if ($line -match '^C ') { break }

    # A vendor line has no leading tab. Tab-indented lines are that vendor's products and
    # interfaces.
    if ($line -match '^([0-9a-fA-F]{4})  (.+)$') {
        $id = [Convert]::ToInt32($Matches[1], 16)
        $name = $Matches[2].Trim()
        if ($vendors.ContainsKey($id)) { throw "usb.ids lists vendor $($Matches[1]) twice." }
        if ($name.Contains("`t")) { throw "vendor $($Matches[1]) has a tab in its name." }
        $vendors.Add($id, $name)
    }
}

if (-not $version -or -not $date) { throw 'usb.ids has no Version or Date header; is this the right file?' }

# A truncated download or an error page would otherwise silently become an almost empty table.
if ($vendors.Count -lt 1000) { throw "only $($vendors.Count) vendors found; refusing to write a table that small." }

$out = [System.Collections.Generic.List[string]]::new()
$out.Add('# USB vendor IDs and the name registered to each: four hex digits, a tab, the name.')
$out.Add('# A registered name says who holds the ID. It is not proof of who made a given device.')
$out.Add('# Generated by scripts/update-usb-vendors.ps1 from the USB ID Repository,')
$out.Add('# http://www.linux-usb.org/usb.ids. Vendor lines only; products and classes are left out.')
$out.Add("# Source version: $version ($date)")
$out.Add('# Used under the 3-clause BSD License, one of the two licences the repository offers')
$out.Add('# (the other is GPL-2.0-or-later). See THIRD-PARTY-NOTICES.md.')
foreach ($entry in $vendors.GetEnumerator()) {
    $out.Add(('{0:X4}' -f $entry.Key) + "`t" + $entry.Value)
}

[System.IO.File]::WriteAllText($target, ($out -join "`r`n") + "`r`n", [System.Text.UTF8Encoding]::new($false))

Write-Host "Wrote $($vendors.Count) vendors from usb.ids $version ($date) to $target"
Write-Host 'Now update the version and date in THIRD-PARTY-NOTICES.md to match.'
